### PR TITLE
Updated PHP dependencies to the latest versions

### PR DESCRIPTION
**Pull request by sebastiaanspeck**
Updated PHP dependencies to the latest versions

#1

### CODE REVIEW

**Comment by muspelheim** [comment]
@sebastiaanspeck where is composer.json file? we do not need compose.lock here

**Comment by sebastiaanspeck** [comment]
I ran ‘composer update’ and all that changed was the creation of composer.lock

**Comment by sebastiaanspeck** [comment]
Why did you close it?

**Comment by muspelheim** [comment]
@sebastiaanspeck sorry, but we dont need composer.lock here. In my issue i mean UP composer.json dependencies to the current versions.

**Pull request closed without merging**
